### ISSUE TITLE
Update agent for pydle 0.8.5+ / python 3.7 fixes

### ISSUE THREAD

**Issue by richteer** [halibot-extra/irc#3]
~~The `irc` agent is completely broken on 3.7 since `async` was made a reserved keyword, thus breaking Pydle.~~

~~See Pydle issue here: https://github.com/Shizmob/pydle/issues/76~~
~~And the relevant pull request that sort of fixes it here: https://github.com/Shizmob/pydle/pull/79~~

~~I see two courses of action for this:~~
~~1. Write a new IRC agent using a different backing library (not a bad idea for variety's sake)~~
~~2. Wait it out for a fix, and warn users not to run with 3.7 (possibly put a warning in the code)~~

Pydle issues have been resolved and now plays nice with 3.7 again.

However, the agent needs to be updated for these changes, as we now need to await on the handling async functions.

Further suggestion: investigate notifying users if they have potentially incompatible python/pydle versions? Make 0.8.5 mandatory?

**Comment by richteer** [comment]
I am currently running a version of pydle with that pull request applied, and it seems to work after commenting out the `pydle.coroutine` lines (as that wrapper lib was removed). Will post further when I have more information.

**Comment by theunkn0wn1** [comment]
An update for Pydle should be released soon resolving the 3.7 incompatability. 

I have also re-implemented `pydle.coroutine` as not to require that change on your end, I should have been more careful to observe downstream usages prior to changing the interface.  I will be more careful not to change the interface moving forward to minimize the likelihood of breaking things unnecessarily.

**Comment by theunkn0wn1** [comment]
pydle `v0.8.5` has been released, which resolves the python 3.7 incompatibility.

**Comment by richteer** [comment]
Thanks for the heads up on the fix!

Leaving issue open since the agent still needs to be updated, but that thankfully resolved the main problem.

**Comment by theunkn0wn1** [comment]
No worries. Just a heads up version 0.8.5 has a couple show-stopping bugs revolving around reconnection handling and suggest using `v0.9.0`+

Sorry for any inconvenience this may cause!
